set nocompatible  "关闭与VI的兼容
set rnu  "显示行号
filetype on 
set history=1000 
set background=dark "设置背景为灰色
syntax on  "打开语法高亮显示
set autoindent "自动对齐，使用上一行的对齐方式
set smartindent "智能对齐方式
set tabstop=4
set shiftwidth=4
set showmatch  "设置匹配模式，类似当输入一个左括号时匹配上相应的那个右括号
set guioptions-=T
set vb t_vb=
set ruler "在编辑过程中，在右下角显示光标位置的状态行
set nohls  
set incsearch "搜索自动定位
if has("vms")
set nobackup
else
set backup
endif

" F2 enter paste mode
set pastetoggle=<F2>

" 折叠方式
" set foldmethod=indent
" 高亮搜索
set hlsearch

" colorscheme hybrid
" 使用jj 进入normal 模式
inoremap jj <Esc>`^

" 使用 leader + w 直接保存
let mapleader = ','
inoremap <leader>w <Esc>:w<CR>
inoremap <leader>wq <Esc>:wq<CR>
inoremap <leader>q <Esc>:q!<CR>
nnoremap <leader>w :w<CR>

" 切换 buffer 
nnoremap <silent> [b :bprevious<CR>
nnoremap <silent> [n :bnext<CR>

" user ctl +h/j/k/l switch window
noremap <C-h> <C-w>h
noremap <C-j> <C-w>j
noremap <C-k> <C-w>k
noremap <C-l> <C-w>l

call plug#begin('~/.vim/plugged')
" Initialize plugin system
Plug 'mhinz/vim-startify'
Plug 'scrooloose/nerdtree'
Plug 'majutsushi/tagbar'
Plug 'lfv89/vim-interestingwords'
Plug 'vim-airline/vim-airline'
Plug 'vim-airline/vim-airline-themes'
Plug 'ycm-core/YouCompleteMe'
Plug 'MattesGroeger/vim-bookmarks'
Plug 'easymotion/vim-easymotion'
Plug 'scrooloose/nerdcommenter'
" Plug 'sillybun/vim-autodoc'
Plug 'heavenshell/vim-pydocstring'
call plug#end()

nmap ,v  :NERDTreeFind<CR>
nmap ,g  :NERDTreeToggle<CR>
nmap ,tt :TagbarToggle<CR>

highlight BookmarkSign ctermbg=NONE ctermfg=160
highlight BookmarkLine ctermbg=194 ctermfg=NONE
let g:bookmark_sign = '♥'
let g:bookmark_highlight_lines = 1
